-- 보호소에 들어온 기록이 없고, 입양을 간 기록은 있는 동물의 ID와 이름을 ID순으로 조회
-- ANIMAL_INS(보호소들어온 기록) , ANIMAL_OUTS(입양보낸기록)
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
LEFT OUTER JOIN ANIMAL_INS B ON B.ANIMAL_ID = A.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.ANIMAL_ID